# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: utf8
  reconnect: true
  database: home-money
  pool: 15
  password: 123


production:
  adapter: postgresql
  encoding: utf8
  reconnect: true
  database: home-money
  pool: 15
  password: 123
